"""
Module 3: exploratory_plotting
-------------------------------
Generates publication‑quality plots from the outputs of modules 1 and 2.
Uses filtered sample mapping for PCA colouring.
Plots are saved in both PDF (publication) and PNG (quick viewing) formats.
If required input files are missing, logs a helpful message suggesting which module to run.
"""

import os
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
from . import utils

def run(variant_qc_dir, compare_dir, output_dir, params):
    """
    Main entry point for exploratory_plotting module.
    """
    logger = utils.get_logger()
    module_out = os.path.join(output_dir, "exploratory_plotting")
    os.makedirs(module_out, exist_ok=True)

    # Set plotting style
    if params.get('plot_style', 'publication') == 'publication':
        utils.set_publication_style()

    # We always save both PDF and PNG
    formats = ['pdf', 'png']

    # -------------------------------------------------------------------------
    # 1. RNA‑specific metric distributions (from variant_qc)
    metrics_file = os.path.join(variant_qc_dir, "rna_metrics.tsv")
    if os.path.exists(metrics_file):
        _plot_metrics_distributions(metrics_file, module_out, formats)
    else:
        logger.info("  RNA metrics file not found: %s", metrics_file)
        logger.info("    This file is generated by the 'variant_qc' module.")
        logger.info("    To generate it, enable 'variant_qc: true' in your config and rerun the pipeline.")

    # -------------------------------------------------------------------------
    # 2. Concordance summary plots (from compare_wgs_rnaseq)
    concord_file = os.path.join(compare_dir, "concordance_summary.tsv")
    if os.path.exists(concord_file):
        _plot_concordance(concord_file, module_out, formats)
    else:
        logger.info("  Concordance summary file not found: %s", concord_file)
        logger.info("    This file is generated by the 'compare_wgs_rnaseq' module.")
        logger.info("    To generate it, enable 'compare_wgs_rnaseq: true' in your config and rerun the pipeline.")

    # -------------------------------------------------------------------------
    # 3. Ti/Tv comparison
    titv_file = os.path.join(compare_dir, "titv_comparison.tsv")
    if os.path.exists(titv_file):
        _plot_titv(titv_file, module_out, formats)
    else:
        logger.info("  Ti/Tv comparison file not found: %s", titv_file)
        logger.info("    This file is generated by the 'compare_wgs_rnaseq' module.")
        logger.info("    To generate it, enable 'compare_wgs_rnaseq: true' in your config and rerun the pipeline.")

    # -------------------------------------------------------------------------
    # 4. PCA and IBS heatmap (requires filtered mapping from compare module)
    vcf_for_pca = os.path.join(compare_dir, "common_sites.vcf.gz")
    filtered_map = os.path.join(compare_dir, "filtered_sample_map.tsv")
    if os.path.exists(vcf_for_pca) and os.path.exists(filtered_map):
        _sample_identity_pca(vcf_for_pca, filtered_map, module_out, formats, params)
    else:
        if not os.path.exists(vcf_for_pca):
            logger.info("  Common sites VCF not found: %s", vcf_for_pca)
        if not os.path.exists(filtered_map):
            logger.info("  Filtered sample map not found: %s", filtered_map)
        logger.info("    These files are generated by the 'compare_wgs_rnaseq' module.")
        logger.info("    To generate them, enable 'compare_wgs_rnaseq: true' in your config and rerun the pipeline.")

    # -------------------------------------------------------------------------
    # 5. ASE analysis plots
    ase_file = os.path.join(compare_dir, "ase_analysis.tsv")
    if os.path.exists(ase_file):
        _plot_ase(ase_file, module_out, formats)
    else:
        logger.info("  ASE analysis file not found: %s", ase_file)
        logger.info("    This file is generated by the 'compare_wgs_rnaseq' module.")
        logger.info("    To generate it, enable 'compare_wgs_rnaseq: true' in your config and rerun the pipeline.")

    logger.info(f"  Plotting completed. Results in {module_out}")

def _save_fig(fig, base_path, formats):
    """Save figure in multiple formats and close."""
    for fmt in formats:
        fig.savefig(f"{base_path}.{fmt}", dpi=300, bbox_inches='tight')
    plt.close(fig)

def _plot_metrics_distributions(metrics_tsv, out_dir, formats):
    """
    Histograms of RNA‑specific metrics: VDB, RPB, MQB, BQB, MQ0F, DP, QD.
    Robustly handles mixed data types by converting to numeric and dropping NaN.
    Saves a multi‑panel figure.
    """
    logger = utils.get_logger()
    df = pd.read_csv(metrics_tsv, sep='\t')
    metrics = ['VDB', 'RPB', 'MQB', 'BQB', 'MQ0F', 'DP', 'QD']
    n_plots = len(metrics)
    n_cols = 3
    n_rows = int(np.ceil(n_plots / n_cols))
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(4*n_cols, 3*n_rows))
    axes = axes.flatten()

    for i, met in enumerate(metrics):
        ax = axes[i]
        if met in df.columns:
            # Convert to numeric, coerce errors to NaN, drop NaN
            data = pd.to_numeric(df[met], errors='coerce').dropna()
            if len(data) == 0:
                ax.text(0.5, 0.5, 'No numeric data', ha='center', va='center')
                ax.set_title(met)
                continue
            # Remove extreme outliers for DP
            if met == 'DP':
                data = data[data < np.percentile(data, 99)]
            ax.hist(data, bins=50, alpha=0.7, color='steelblue', edgecolor='black')
            ax.set_title(met)
            ax.set_xlabel(met)
            ax.set_ylabel('Frequency')
        else:
            ax.text(0.5, 0.5, f'{met} not found', ha='center', va='center')
            ax.set_title(met)

    # Hide any unused subplots
    for j in range(i+1, len(axes)):
        axes[j].set_visible(False)

    plt.tight_layout()
    base = os.path.join(out_dir, 'rna_metrics_dist')
    _save_fig(plt.gcf(), base, formats)
    logger.info(f"  Saved RNA metrics distribution plots to {base}.{formats[0]}, {base}.{formats[1]}")

def _plot_concordance(concord_tsv, out_dir, formats):
    """
    Generate bar plot of precision, recall, concordance per sample.
    Also create a scatter plot of precision vs recall.
    """
    logger = utils.get_logger()
    df = pd.read_csv(concord_tsv, sep='\t')

    # Bar plot
    df_melt = df.melt(id_vars=['rna_sample','wgs_sample'],
                      value_vars=['precision','recall','concordance'],
                      var_name='metric', value_name='value')
    fig1 = plt.figure(figsize=(max(8, 0.3 * len(df)), 6))
    sns.barplot(data=df_melt, x='rna_sample', y='value', hue='metric')
    plt.xticks(rotation=90)
    plt.ylabel('Score')
    plt.title('Per‑sample concordance metrics')
    plt.legend(loc='lower right')
    plt.tight_layout()
    base1 = os.path.join(out_dir, 'concordance_bars')
    _save_fig(plt.gcf(), base1, formats)

    # Scatter plot
    fig2 = plt.figure(figsize=(6,6))
    sns.scatterplot(data=df, x='precision', y='recall', hue='rna_sample', s=100)
    plt.xlim(0, 1)
    plt.ylim(0, 1)
    plt.plot([0, 1], [0, 1], 'k--', alpha=0.5)
    plt.xlabel('Precision')
    plt.ylabel('Recall')
    plt.title('Precision vs Recall')
    plt.tight_layout()
    base2 = os.path.join(out_dir, 'precision_recall')
    _save_fig(plt.gcf(), base2, formats)

    logger.info(f"  Saved concordance plots to {base1}.{formats[0]}, {base2}.{formats[0]} etc.")

def _plot_titv(titv_file, out_dir, formats):
    """
    Bar chart comparing RNA and WGS Ti/Tv ratios per sample.
    """
    logger = utils.get_logger()
    df = pd.read_csv(titv_file, sep='\t')
    df_melt = df.melt(id_vars=['rna_sample','wgs_sample'],
                      value_vars=['rna_titv','wgs_titv'],
                      var_name='source', value_name='titv')
    fig = plt.figure(figsize=(max(8, 0.3 * len(df)), 6))
    sns.barplot(data=df_melt, x='rna_sample', y='titv', hue='source')
    plt.xticks(rotation=90)
    plt.ylabel('Ti/Tv ratio')
    plt.axhline(y=2.0, color='gray', linestyle='--', label='Expected DNA Ti/Tv ~2.0')
    plt.axhline(y=2.8, color='lightgray', linestyle='--', label='Expected RNA Ti/Tv ~2.5‑3.0')
    plt.legend()
    plt.tight_layout()
    base = os.path.join(out_dir, 'titv_comparison')
    _save_fig(plt.gcf(), base, formats)
    logger.info(f"  Saved Ti/Tv comparison plot to {base}.{formats[0]}, {base}.{formats[1]}")

def _sample_identity_pca(vcf, filtered_map, out_dir, formats, params):
    """
    Perform PCA on a subset of common SNPs and generate IBS heatmap.
    Uses filtered mapping to colour points correctly.
    Now includes safeguards for empty genotype matrices.
    """
    logger = utils.get_logger()
    from sklearn.decomposition import PCA
    from sklearn.metrics import pairwise_distances

    n_sites = params.get('pca_n_sites', 1000)
    min_maf = params.get('pca_min_maf', 0.05)

    # Get list of samples
    samples = utils.get_vcf_samples(vcf)

    # Load filtered mapping to know which are RNA and which are WGS
    mapping_df = pd.read_csv(filtered_map, sep='\t', header=None, names=['rna','wgs'])
    rna_set = set(mapping_df['rna'])
    wgs_set = set(mapping_df['wgs'])

    sample_type = {}
    for s in samples:
        if s in rna_set:
            sample_type[s] = 'RNA'
        elif s in wgs_set:
            sample_type[s] = 'WGS'
        else:
            sample_type[s] = 'unknown'

    # Randomly select n_sites biallelic SNPs
    tmp_sites = os.path.join(out_dir, "pca_sites.txt")
    cmd = f"bcftools view -v snps -m2 -M2 {vcf} | bcftools query -f '%CHROM\t%POS\n' | shuf -n {n_sites} > {tmp_sites}"
    utils.run_cmd(cmd, "Selecting random sites for PCA")

    # Extract genotype matrix (0,1,2) for all samples at those sites
    # Correct format: no trailing tab, each sample's GT separated by tabs
    cmd = f"bcftools query -R {tmp_sites} -f '[%CHROM:%POS\t%GT]\n' {vcf} > {out_dir}/pca_raw.tsv"
    utils.run_cmd(cmd, "Extracting genotypes for PCA")

    # Parse the raw file
    raw = pd.read_csv(f"{out_dir}/pca_raw.tsv", sep='\t', header=None)
    site_ids = raw.iloc[:,0]
    geno_raw = raw.iloc[:,1:]

    # Convert GT to numeric
    def gt_to_int(gt):
        if gt in ('0/0', '0|0'):
            return 0
        elif gt in ('0/1', '0|1', '1/0', '1|0'):
            return 1
        elif gt in ('1/1', '1|1'):
            return 2
        else:
            return np.nan

    # Use .map instead of deprecated .applymap
    geno = geno_raw.map(gt_to_int)
    geno.columns = samples
    geno.index = site_ids

    # Filter by MAF
    maf = geno.apply(lambda row: (row==1).sum() + 2*(row==2).sum(), axis=1) / (2 * geno.shape[1])
    geno = geno[(maf >= min_maf) & (maf <= 1-min_maf)]

    if geno.shape[0] == 0:
        logger.warning("  No sites passed MAF filtering; skipping PCA and IBS heatmap.")
        return

    # Impute missing values with mean
    geno = geno.fillna(geno.mean(axis=1), axis=0)

    # Check if we have at least 2 sites
    if geno.shape[0] < 2:
        logger.warning("  Less than 2 sites after filtering; skipping PCA and IBS heatmap.")
        return

    # PCA
    pca = PCA(n_components=2)
    coords = pca.fit_transform(geno.T)

    # Plot PCA
    fig1 = plt.figure(figsize=(8,6))
    colors = {'RNA':'red', 'WGS':'blue', 'unknown':'gray'}
    point_colors = [colors[sample_type[s]] for s in samples]
    plt.scatter(coords[:,0], coords[:,1], c=point_colors, alpha=0.7, s=50)
    for i, s in enumerate(samples):
        plt.annotate(s, (coords[i,0], coords[i,1]), fontsize=8, alpha=0.7)
    plt.xlabel('PC1 ({:.1f}%)'.format(pca.explained_variance_ratio_[0]*100))
    plt.ylabel('PC2 ({:.1f}%)'.format(pca.explained_variance_ratio_[1]*100))
    plt.title('PCA of genotypes (red=RNA, blue=WGS)')
    plt.tight_layout()
    base1 = os.path.join(out_dir, 'pca')
    _save_fig(plt.gcf(), base1, formats)

    # IBS heatmap (use sites with no missing data)
    geno_complete = geno.T.dropna(axis=1)
    if geno_complete.shape[1] == 0:
        logger.info("  No complete sites for IBS heatmap; skipping.")
        return
    dist = pairwise_distances(geno_complete, metric='manhattan')
    max_dist = 2 * geno_complete.shape[1]
    ibs = 1 - (dist / max_dist)

    fig2 = plt.figure(figsize=(10,8))
    sns.heatmap(ibs, xticklabels=samples, yticklabels=samples,
                cmap='viridis', vmin=0.5, vmax=1,
                square=True, cbar_kws={'label': 'IBS similarity'})
    plt.title('IBS similarity matrix')
    plt.tight_layout()
    base2 = os.path.join(out_dir, 'ibs_heatmap')
    _save_fig(plt.gcf(), base2, formats)
    logger.info(f"  Saved PCA and IBS plots to {base1}.{formats[0]}, {base2}.{formats[0]} etc.")

def _plot_ase(ase_file, out_dir, formats):
    """
    Scatter plot of WGS alt ratio vs RNA alt ratio, and histogram of deviations.
    """
    logger = utils.get_logger()
    df = pd.read_csv(ase_file, sep='\t')
    if df.empty:
        logger.info("  ASE file empty; skipping plots.")
        return

    # Scatter plot
    fig1 = plt.figure(figsize=(6,6))
    sns.scatterplot(data=df, x='wgs_alt_ratio', y='rna_alt_ratio',
                    alpha=0.3, s=30, color='steelblue')
    plt.plot([0, 1], [0, 1], 'r--', alpha=0.5)
    plt.xlabel('WGS alternative allele ratio')
    plt.ylabel('RNA alternative allele ratio')
    plt.title('Allelic balance: WGS vs RNA')
    plt.tight_layout()
    base1 = os.path.join(out_dir, 'ase_scatter')
    _save_fig(plt.gcf(), base1, formats)

    # Histogram of deviations
    df['deviation'] = df['rna_alt_ratio'] - df['wgs_alt_ratio']
    fig2 = plt.figure(figsize=(8,4))
    sns.histplot(df['deviation'], bins=50, color='steelblue', edgecolor='black')
    plt.xlabel('RNA ratio - WGS ratio')
    plt.ylabel('Frequency')
    plt.title('Allelic imbalance distribution')
    plt.tight_layout()
    base2 = os.path.join(out_dir, 'ase_deviation')
    _save_fig(plt.gcf(), base2, formats)
    logger.info(f"  Saved ASE plots to {base1}.{formats[0]}, {base2}.{formats[0]} etc.")